# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# 이미지 저장
#, image: Rails.root.join("app/assets/images/**.jpg").open

# 추천 제1경로
Recom.create(title: '청구역', address: '서울특별시 중구 청구로 77', latitude: 37.5603311, longitude: 127.013855)
Recom.create(title: 'CCTV', address: '서울특별시 중구 신당동 304-693', latitude: 37.56077970956365, longitude: 127.01319695402124)
Recom.create(title: '안전비상벨', address: '서울특별시 중구 신당동 297-17', latitude: 37.5609238471306, longitude: 127.013391651867)
Recom.create(title: '세븐일레븐 청구점', address: '서울특별시 중구 다산로29길14', latitude: 37.56111847979138, longitude: 127.01323775927098)
Recom.create(title: 'GS25 광희청구점', address: '서울특별시 중구 청구로14길18', latitude: 37.56157627563474, longitude: 127.01241387073424)
Recom.create(title: 'CCTV', address: '서울특별시 중구 신당동 304-93', latitude: 37.562906055555544, longitude: 127.01325165771355)


# 추천 제2경로
Recom.create(title: '청구역', address: '서울특별시 중구 청구로 77', latitude: 37.5603311, longitude: 127.013855)
Recom.create(title: '안전비상벨', address: '서울특별시 중구 신당동 297-17', latitude: 37.560923847130624, longitude: 127.0133916518675)
Recom.create(title: 'CCTV', address: '서울특별시 중구 신당동 304-693', latitude: 37.56077970956365, longitude: 127.01319695402124)
Recom.create(title: '세븐일레븐 청구점', address: '서울특별시 중구 다산로29길14', latitude: 37.56111847979138, longitude: 127.01323775927098)
Recom.create(title: '안전비상벨', address: '서울특별시 중구 신당동 298-74', latitude: 37.56138150655941, longitude: 127.0137991901829)
#Recom.create(title: 'CCTV', address: '서울특별시 중구 신당동 304-720', latitude: 37.562192356850574, longitude: 127.01419321852322)
Recom.create(title: 'CCTV', address: '서울특별시 중구 신당동 304-362', latitude: 37.56181400233214, longitude: 127.01364986840635)
Recom.create(title: 'CCTV', address: '서울특별시 중구 신당동 304-370', latitude: 37.56201226392752, longitude: 127.01327866339335)
Recom.create(title: 'CCTV', address: '서울특별시 중구 신당동 304-93', latitude: 37.562906055555544, longitude: 127.01325165771355)
	


# Bank.create(bank: 'BNK저축은행', name: '정기예금', region1: '서울', region2: '부산', region3:'경남', price1: 1.2, price2: 1.8, price3: 1.9, price4: 1.9, contactOptions: true, rank: 31, url: 'https://www.bnksb.com/')
# Bank.create(bank: 'CK저축은행', name: '정기예금', region1: '강원', price1: 1.6, price2: 1.9, price3: 1.95, price4: 2, contactOptions: true, rank: 64, url: 'https://www.cksavingsbank.co.kr/main.act')
# Bank.create(bank: 'CK저축은행', name: '정기예금(인터넷모바일비대면)', region1: '강원', price1: 1.6, price2: 1.0, price3: 1.95, price4: 2, contactOptions: false, rank: 64, url:'https://www.cksavingsbank.co.kr/main.act')
# Bank.create(bank: 'DB저축은행', name: '정기예금', region1: '서울', price1: 1.4, price2: 1.9, price3: 1.9, price4: 0, contactOptions: true, rank: 27, url: 'https://www.idbsb.com/') 
# Bank.create(bank: 'DH저축은행', name: '정기예금', region1: '부산', price1: 1.6, price2: 1.9, price3: 1.9, price4: 0, contactOptions: true, rank: 63, url: 'https://www.dhsavingsbank.co.kr/main.act')
# Bank.create(bank: 'DH저축은행', name: '정기예금(비대면)', region1: '부산', price1: 1.6, price2: 2, price3: 2, price4: 0, contactOptions: false, rank: 63, url:'https://www.dhsavingsbank.co.kr/main.act')
# Bank.create(bank: 'IBK저축은행', name: '참기특한 정기예금', region1: '서울', region2: '부산', region3: '경남', region4: '대구', price1: 1.6, price2: 1.7, price3: 1.8, price4: 1.8, contactOptions: true, rank: 38, url: 'https://www.ibksb.co.kr/')
# Bank.create(bank: 'IBK저축은행(비대면)', name: '참기특한 정기예금(비대면)', region1: '서울', region2: '부산', region3: '경남', region4: '대구', price1: 1.6, price2: 1.8, price3: 1.9, price4: 1.9, contactOptions: false, rank: 38, url: 'https://www.ibksb.co.kr/')
# Bank.create(bank: 'JT저축은행', name: 'e-정기예금', region1: '경기', region2: '광주', region3: '전남',price1: 1.5, price2: 1.9, price3: 1.9, price4: 1.9, contactOptions: false, rank: 17, url: 'https://www.jt-bank.co.kr/')
# Bank.create(bank: 'JT저축은행', name: '회전식 정기예금(변동금리상품)', region1: '경기', region2: '광주', region3: '전남',price1: 0, price2: 2, price3: 2, price4: 2, contactOptions: true, rank: 17, url: 'https://www.jt-bank.co.kr/')
# Bank.create(bank: 'JT저축은행', name: '회전식 정기예금_비대면(변동금리상품)', region1: '경기', region2: '광주', region3: '전남',price1: 0, price2: 2, price3: 2, price4: 2, contactOptions: false, rank: 17, url: 'https://www.jt-bank.co.kr/')
# Bank.create(bank: 'JT저축은행', name: '정기예금', region1: '경기', region2: '광주', region3: '전남', price1: 1.5, price2: 1.9, price3: 1.9, price4: 1.9, contactOptions: true, rank: 17, url: 'https://www.jt-bank.co.kr/')
# Bank.create(bank: 'JT친애저축은행', name: '비대면 정기예금', region1: '서울', region2: '광주', region3: '충남', region4: '제주', region5: '전북', region6: '대전', price1: 1.3, price2: 2.15, price3: 2.15, price4: 2.15, contactOptions: false, rank: 10, url: 'https://www.jtchinae-bank.co.kr/usr/index.do')
# Bank.create(bank: 'JT친애저축은행', name: '정기예금', region1: '서울', region2: '광주', region3: '충남', region4: '제주', region5: '전북', region6: '대전', price1: 1.3, price2: 1.9, price3: 2, price4: 2, contactOptions: true, rank: 10, url: 'https://www.jtchinae-bank.co.kr/usr/index.do')
# Bank.create(bank: 'JT친애저축은행', name: '회전식 정기예금', region1: '서울', region2: '광주', region3: '충남', region4: '제주', region5: '전북', region6: '대전', price1: 0, price2: 2, price3: 2, price4: 2, contactOptions: true, rank: 10, url: 'https://www.jtchinae-bank.co.kr/usr/index.do')
# Bank.create(bank: 'KB저축은행', name: '정기예금', region1: '서울', region2: '인천', region3: '경기', price1: 1.5, price2: 1.8, price3: 1.7, price4: 1.6, contactOptions: true, rank: 26, url: 'https://www.kbsavings.com/')
# Bank.create(bank: 'KB저축은행', name: 'KB e-plus 정기예금', region1: '서울', region2: '인천', region3: '경기', price1: 1.6, price2: 1.9, price3: 1.8, price4: 1.7, contactOptions: false, rank: 26, url: 'https://www.kbsavings.com/')
# Bank.create(bank: 'NH저축은행', name: '비대면 정기예금', region1: '서울', region2: '경남', region3: '경북', region4: '전남', price1: 1.6, price2: 1.9, price3: 2, price4: 0, contactOptions: false, rank: 19, url: 'https://www.nhsavingsbank.co.kr/')
# Bank.create(bank: 'NH저축은행', name: '중도해지 Good 정기예금', region1: '서울', region2: '경남', region3: '경북', region4: '전남', price1: 0, price2: 0, price3: 1.9, price4: 0, contactOptions: true, rank: 19, url: 'https://www.nhsavingsbank.co.kr/')
# Bank.create(bank: 'NH저축은행', name: '정기예금', region1: '서울', region2: '경남', region3: '경북', region4: '전남', price1: 1.5, price2: 1.8, price3: 1.9, price4: 0, contactOptions: true, rank: 19, url: 'https://www.nhsavingsbank.co.kr/')
# Bank.create(bank: 'OK저축은행', name: '중도해지OK정기예금', region1: '서울', region2: '인천', region3: '경기', region4: '대전', region5: '충남', region6: '전북', price1: 1.6, price2: 1.6, price3: 1.6, price4: 1.6, contactOptions: true, rank: 2, url: 'https://www.oksavingsbank.com/')
# Bank.create(bank: 'OK저축은행', name: 'OK안심정기예금(변동금리)', region1: '서울', region2: '인천', region3: '경기', region4: '대전', region5: '충남', region6: '전북', price1: 0, price2: 2.1, price3: 2.1, price4: 2.1, contactOptions: true, rank: 2, url: 'https://www.oksavingsbank.com/')
# Bank.create(bank: 'OK저축은행', name: 'OK정기예금', region1: '서울', region2: '인천', region3: '경기', region4: '대전', region5: '충남', region6: '전북', price1: 0, price2: 2, price3: 0, price4: 0, contactOptions: true, rank: 2, url: 'https://www.oksavingsbank.com/')
# Bank.create(bank: 'OSB저축은행', name: 'CD연동장기정기예금', region1: '서울', region2: '인천', region3: '경기', region4: '부산', region5: '전북',price1: 0, price2: 0, price3: 2.2, price4: 2.3, contactOptions: true, rank: 14, url: 'https://www.osb.co.kr/ib20/mnu/HOM00001')
# Bank.create(bank: 'OSB저축은행', name: '정기예금', region1: '서울', region2: '인천', region3: '경기', region4: '부산', region5: '전북', price1: 1.6, price2: 2, price3: 2.1, price4: 2.2, contactOptions: true, rank: 14, url: 'https://www.osb.co.kr/ib20/mnu/HOM00001')
# Bank.create(bank: 'SBI저축은행', name: '정기예금', region1: '서울', region2: '인천', region3: '경기', region4: '대구', region5: '대전', price1: 1.3, price2: 2, price3: 2, price4: 2, contactOptions: true, rank: 1, url: 'http://www.babilloan.com/')
# Bank.create(bank: 'SBI저축은행', name: 'SBI스페셜 정기예금', region1: '서울', region2: '인천', region3: '경기', region4: '대구', region5: '대전', price1: 0, price2: 0, price3: 0, price4: 2, contactOptions: true, rank: 1, url: 'http://www.babilloan.com/')
# Bank.create(bank: '고려저축은행', name: '회전정기예금(비대면)', region1: '부산', region2: '대구', price1: 0, price2: 1.8, price3: 1.8, price4: 1.8, contactOptions: false, rank: 11, url: 'https://www.goryosb.co.kr/')
# Bank.create(bank: '고려저축은행', name: '회전정기예금', region1: '부산', region2: '대구', price1: 0, price2: 1.8, price3: 1.8, price4: 1.8, contactOptions: true, rank: 11, url: 'https://www.goryosb.co.kr/')
# Bank.create(bank: '고려저축은행', name: '정기예금(비대면)', region1: '부산', region2: '대구', price1: 1.3, price2: 1.7, price3: 1.8, price4: 1.9, contactOptions: false, rank: 11, url: 'https://www.goryosb.co.kr/')
# Bank.create(bank: '고려저축은행', name: '정기예금', region1: '부산', region2: '대구', price1: 1.3, price2: 1.7, price3: 1.8, price4: 1.9, contactOptions: true, rank: 11, url: 'https://www.goryosb.co.kr/')
# Bank.create(bank: '국제저축은행', name: '꿈 찾아 정기예금', region1: '부산', price1: 1.3, price2: 1.9, price3: 1.9, price4: 0, contactOptions: true, rank: 48, url: 'https://www.kukjebank.co.kr/')
# Bank.create(bank: '국제저축은행', name: 'S-꿈 찾아 정기예금', region1: '부산', price1: 1.3, price2: 1.9, price3: 1.9, price4: 0, contactOptions: true, rank: 48, url: 'https://www.kukjebank.co.kr/')
# Bank.create(bank: '국제저축은행', name: '꿈 찾아 정기예금(비대면)', region1: '부산', price1: 1.3, price2: 1.9, price3: 1.9, price4: 0, contactOptions: true, rank: 48, url: 'https://www.kukjebank.co.kr/')
# Bank.create(bank: '국제저축은행', name: 'E-꿈 찾아 정기예금', region1: '부산', price1: 1.3, price2: 1.9, price3: 1.9, price4: 0, contactOptions: true, rank: 48, url: 'https://www.kukjebank.co.kr/')
# Bank.create(bank: '금화저축은행', name: '비대면-정기예금', region1: '인천', price1: 1.6, price2: 2.1, price3: 2.2, price4: 2.2, contactOptions: false, rank: 22, url: 'https://www.kuemhwabank.co.kr/')
# Bank.create(bank: '금화저축은행', name: 'e-정기예금', region1: '인천', price1: 1.6, price2: 2.1, price3: 2.2, price4: 2.2, contactOptions: false, rank: 22, url: 'https://www.kuemhwabank.co.kr/')
# Bank.create(bank: '금화저축은행', name: '정기예금', region1: '인천', price1: 1.5, price2: 2, price3: 2.1, price4: 2.1, contactOptions: true, rank: 22, url: 'https://www.kuemhwabank.co.kr/')
# Bank.create(bank: '남양저축은행', name: '정기예금', region1: '경기', price1: 1.6, price2: 2, price3: 2.1, price4: 0, contactOptions: true, rank: 20, url: 'https://www.nybank.co.kr/')
# Bank.create(bank: '남양저축은행', name: '비대면-정기예금', region1: '경기', price1: 1.7, price2: 2.1, price3: 2.2, price4: 0, contactOptions: false, rank: 20, url: 'https://www.nybank.co.kr/')
# Bank.create(bank: '대명저축은행', name: 'E-플러스 정기예금', region1: '충북', price1: 0, price2: 2.15, price3: 0, price4: 0, contactOptions: false, rank: 73, url: 'https://www.daemyungbank.co.kr/')
# Bank.create(bank: '대명저축은행', name: '행복플러스 정기예금', region1: '충북', price1: 0, price2: 2.25, price3: 0, price4: 0, contactOptions: true, rank: 73, url: 'https://www.daemyungbank.co.kr/')
# Bank.create(bank: '대명저축은행', name: '정기예금', region1: '충북', price1: 1.6, price2: 2.2, price3: 0, price4: 0, contactOptions: true, rank: 73, url: 'https://www.daemyungbank.co.kr/')
# Bank.create(bank: '대백저축은행', name: '애플정기예금', region1: '대구', price1: 1.7, price2: 2.1, price3: 2.3, price4: 2.3, contactOptions: true, rank: 78, url: 'https://www.debecbank.co.kr/')
# Bank.create(bank: '대백저축은행', name: '정기예금', region1: '대구', price1: 1.7, price2: 2.1, price3: 2.3, price4: 2.3, contactOptions: true, rank: 78, url: 'https://www.debecbank.co.kr/')
# Bank.create(bank: '대신저축은행', name: '정기예금', region1: '서울', region2: '부산', region3: '강원', price1: 1.5, price2: 1.75, price3: 1.75, price4: 1.75, contactOptions: true, rank: 15, url: 'https://bank.daishin.com/')
# Bank.create(bank: '대신저축은행', name: '스마트정기예금_모바일', region1: '서울', region2: '부산', region3: '강원', price1: 1.7, price2: 2, price3: 2, price4: 2, contactOptions: false, rank: 15, url:'https://bank.daishin.com/')
# Bank.create(bank: '대아저축은행', name: '정기예금', region1: '대구', region2: '경북', price1: 1.5, price2: 2, price3: 1.8, price4: 1.8, contactOptions: true, rank: 77,  url:'https://daeabank.com/')
# Bank.create(bank: '대원저축은행', name: '정기예금', region1: '경북', price1: 1.5, price2: 2, price3: 1.8, price4: 1.8, contactOptions: true, rank: 79, url:'https://d-banks.co.kr/')
# Bank.create(bank: '대한저축은행', name: '정기예금', region1: '광주', price1: 1.5, price2: 2.1, price3: 2.1, price4: 0, contactOptions: true, rank: 61, url:'https://www.daehanbank.co.kr/')
# Bank.create(bank: '더블저축은행', name: '정기예금',  region1: '광주', price1: 1.3 , price2: 2.25, price3: 2.25, price4: 2.25, contactOptions: true, rank: 57, url:'https://www.doublebank.co.kr/main.act')    
# Bank.create(bank: '더블저축은행', name: '정기예금 (인터넷뱅킹 스마트뱅킹)', region1: '광주', price1: 1.3, price2: 2.2, price3: 2.2, price4: 2.2, contactOptions: false, rank: 57, url:'https://www.doublebank.co.kr/main.act')
# Bank.create(bank: '더케이저축은행', name: 'e-정기예금', region1: '서울', price1: 1.9 , price2: 1.9, price3: 2.0 , price4: 2.1, contactOptions: false, rank: 30, url:'https://www.thekbank.co.kr/main/main.do')
# Bank.create(bank: '더케이저축은행', name: '정기예금', region1: '서울',  price1: 1.8 , price2: 1.7 , price3: 1.8 , price4: 1.9, contactOptions: true, rank: 30, url:'https://www.thekbank.co.kr/main/main.do')
# Bank.create(bank: '동양저축은행', name: '정기예금', region1: '광주', price1: 1.6 , price2: 2.0 , price3: 2.05 , price4: 2.1, contactOptions: true, rank: 50, url:'https://www.dysbank.com/main.act')
# Bank.create(bank: '동원제일저축은행', name: '회전정기예금-비대면(변동금리)', region1: '부산',  region2: '경남', price1: 0.0 , price2: 1.95 , price3: 1.95 , price4: 1.95, contactOptions: false, rank: 40, url:'https://dongwonjeilbank.kr/main.html')
# Bank.create(bank: '동원제일저축은행', name: '회전정기예금(변동금리)', region1: '부산',  region2: '경남', price1: 0.0 , price2: 1.9 , price3: 1.9 , price4: 1.9, contactOptions: true, rank: 40, url:'https://dongwonjeilbank.kr/main.html')
# Bank.create(bank: '동원제일저축은행', name: '정기예금(비대면)',region1: '부산',  region2: '경남', price1: 1.7 , price2: 1.9 , price3: 1.9 , price4: 0.0, contactOptions: false, rank: 40, url:'https://dongwonjeilbank.kr/main.html')
# Bank.create(bank: '동원제일저축은행', name: '정기예금', region1: '부산',  region2: '경남', price1: 1.6 , price2: 1.8 , price3: 1.8 , price4: 0.0, contactOptions: false, rank: 40, url:'https://dongwonjeilbank.kr/main.html')
# Bank.create(bank: '드림저축은행', name: '톡톡정기예금 (비대면)', region1: '대구',  region2: '강원', price1: 1.6 , price2: 1.8 , price3: 1.9 , price4: 1.9, contactOptions: false, rank: 39, url:'https://www.dreamsb.com/main.act')
# Bank.create(bank: '드림저축은행', name: '정기예금', region1: '대구',  region2: '강원',  price1: 1.6 , price2: 1.8 , price3: 1.9 , price4: 1.9, contactOptions: true, rank: 39, url:'https://www.dreamsb.com/main.act')
# Bank.create(bank: '드림저축은행', name: '자유적립예금', region1: '대구',  region2: '강원',  price1: 1.6 , price2: 1.8 , price3: 1.9 , price4: 1.9, contactOptions: true, rank: 39, url:'https://www.dreamsb.com/main.act')
# Bank.create(bank: '라온저축은행', name: '정기예금', region1: '대구',  region2: '경북',  price1: 0.0 , price2: 1.99 , price3: 1.99 , price4: 1.99, contactOptions: true, rank: 76, url:'https://www.raonsb.co.kr/main.act')
# Bank.create(bank: '라이브저축은행', name: '정기예금', region1: '서울', price1: 1.7 , price2: 2.1 , price3: 2.2 , price4: 2.2, contactOptions: true, rank: 71, url:'https://www.livesb.co.kr/')
# Bank.create(bank: '라이브저축은행', name: '비대면정기예금', region1: '서울', price1: 1.7 , price2: 2.2 , price3: 2.2 , price4: 2.2, contactOptions: false, rank: 71, url:'http://www.livesb.co.kr/')
# Bank.create(bank: '머스트삼일저축은행', name: '비대면정기예금', region1: '경북', price1: 1.6 , price2: 2.0 , price3: 2.1 , price4: 2.1, contactOptions: false, rank: 75, url:'https://www.samilbank.co.kr/main.act')
# Bank.create(bank: '머스트삼일저축은행', name: 'e-정기예금', region1: '경북', price1: 1.6 , price2: 2.0 , price3: 2.1 , price4: 2.1, contactOptions: false, rank: 75, url:'https://www.samilbank.co.kr/main.act')
# Bank.create(bank: '머스트삼일저축은행', name: '정기예금', region1: '경북', price1: 1.6 , price2: 2.0 , price3: 2.1 , price4: 2.1, contactOptions: true, rank: 75, url:'https://www.samilbank.co.kr/main.act')
# Bank.create(bank: '모아저축은행', name: 'e-모아 정기예금', region1: '인천',  region2: '경기', price1: 1.5 , price2: 2.0 , price3: 2.1 , price4: 0.0, contactOptions: false, rank: 6, url:'https://www.moasb.co.kr/main.act')
# Bank.create(bank: '모아저축은행', name: 'e-회전 정기예금', region1: '인천',  region2: '경기', price1: 0.0 , price2: 2.1 , price3: 0.0 , price4: 0.0, contactOptions: false, rank: 6, url:'https://www.moasb.co.kr/main.act')
# Bank.create(bank: '모아저축은행', name: '회전 정기예금', region1: '인천',  region2: '경기', price1: 0.0 , price2: 2.1 , price3: 0.0 , price4: 0.0, contactOptions: true, rank: 6, url:'https://www.moasb.co.kr/main.act')
# Bank.create(bank: '모아저축은행', name: '정기예금', region1: '인천',  region2: '경기',  price1: 1.5 , price2: 2.0 , price3: 2.1 , price4: 0.0, contactOptions: true, rank: 6, url:'https://www.moasb.co.kr/main.act')
# Bank.create(bank: '민국저축은행', name: '톡톡정기예금', region1: '서울', price1: 1.6 , price2: 2.0 , price3: 2.0 , price4: 2.0, contactOptions: true, rank: 28, url:'https://www.mkb.co.kr/main.act')
# Bank.create(bank: '민국저축은행', name: '비대면정기예금', region1: '서울',  price1: 1.6 , price2: 2.0 , price3: 2.0 , price4: 2.0, contactOptions: false, rank: 28, url:'https://www.mkb.co.kr/main.act')
# Bank.create(bank: '민국저축은행', name: '정기예금', region1: '서울',  price1: 1.6 , price2: 1.9 , price3: 1.9 , price4: 1.9, contactOptions: true, rank: 28, url:'https://www.mkb.co.kr/main.act')
# Bank.create(bank: '민국저축은행', name: 'e-행복정기예금', region1: '서울',  price1: 1.6 , price2: 2.0 , price3: 2.0 , price4: 2.0, contactOptions: false, rank: 28, url:'https://www.mkb.co.kr/main.act')
# Bank.create(bank: '바로저축은행', name: '스마트정기예금(인터넷)', region1: '서울',  price1: 1.5 , price2: 2.0 , price3: 2.0 , price4: 2.0, contactOptions: false, rank: 12, url:'https://www.baro-sb.com/main.act')
# Bank.create(bank: '바로저축은행', name: 'SB톡톡 정기예금(비대면)', region1: '서울',  price1: 1.5 , price2: 2.0 , price3: 2.0 , price4: 2.0, contactOptions: false, rank: 12, url:'https://www.baro-sb.com/main.act')
# Bank.create(bank: '바로저축은행', name: '정기예금', region1: '서울',  price1: 1.5 , price2: 1.9 , price3: 1.9 , price4: 1.9, contactOptions: true, rank: 12, url:'https://www.baro-sb.com/main.act')
# Bank.create(bank: '부림저축은행', name: '톡톡정기예금(비대면)', region1: '경기', price1: 1.6 , price2: 2.0 , price3: 2.0 , price4: 0.0, contactOptions: false, rank: 35, url:'https://www.bulimbank.co.kr/main.act')
# Bank.create(bank: '부림저축은행', name: '장기우대 정기예금', region1: '경기', price1: 0.0 , price2: 2.2 , price3: 2.2 , price4: 0.0, contactOptions: true, rank: 35, url:'https://www.bulimbank.co.kr/main.act')
# Bank.create(bank: '부림저축은행', name: '어르신우대 정기예금', region1: '경기', price1: 0.0 , price2: 2.1 , price3: 2.1 , price4: 0.0, contactOptions: true, rank: 35, url:'https://www.bulimbank.co.kr/main.act')
# Bank.create(bank: '부림저축은행', name: '정기예금', region1: '경기', price1: 1.6 , price2: 2.0 , price3: 2.0 , price4: 0.0, contactOptions: true, rank: 35, url:'https://www.bulimbank.co.kr/main.act')
# Bank.create(bank: '삼정저축은행', name: 'e-정기예금', region1: '경기', price1: 1.5 , price2: 2.1 , price3: 2.0 , price4: 0.0, contactOptions: false, rank: 47, url:'https://www.samjungsavingsbank.co.kr/main.act')
# Bank.create(bank: '삼정저축은행', name: 's-정기예금', region1: '경기', price1: 1.5 , price2: 2.1 , price3: 2.0 , price4: 0.0, contactOptions: false, rank: 47, url:'https://www.samjungsavingsbank.co.kr/main.act')
# Bank.create(bank: '삼정저축은행', name: '정기예금', region1: '경기', price1: 1.5 , price2: 2.0 , price3: 2.0 , price4: 0.0, contactOptions: true, rank: 47, url:'https://www.samjungsavingsbank.co.kr/')
# Bank.create(bank: '삼호저축은행', name: '정기예금', region1: '서울', region2: '광주', region3: '전남', region4: '전북', region5: '제주', price1: 1.8 , price2: 2.1 , price3: 2.2 , price4: 2.3, contactOptions: true, rank: 59, url:'https://www.samhosb.co.kr/')
# Bank.create(bank: '삼호저축은행', name: '정기예금(인터넷-모바일)', region1: '서울', region2: '광주', region3: '전남', region4: '전북', region5: '제주', price1: 1.8 , price2: 2.1 , price3: 2.2, price4: 2.3, contactOptions: false, rank: 59, url:'https://www.samhosb.co.kr/main.act/')
# Bank.create(bank: '상상인저축은행', name: '중도해지 괜찮아  정기예금', region1: '경기', price1: 0.0 , price2: 0.0 , price3: 0.0 , price4: 0.0, contactOptions: true, rank: 4, url:'https://www.sangsanginsb.com/service/main/index.jsp')
# Bank.create(bank: '상상인저축은행', name: '비대면 정기예금', region1: '경기', price1: 1.95 , price2: 2.15 , price3: 2.15 , price4: 0.0, contactOptions: false, rank: 4, url:'https://www.sangsanginsb.com/service/main/index.jsp')
# Bank.create(bank: '상상인저축은행', name: '정기예금', region1: '경기', price1: 1.95 , price2: 2.15 , price3: 2.15 , price4: 0.0, contactOptions: true, rank: 4, url:'https://www.sangsanginsb.com/service/main/index.jsp')
# Bank.create(bank: '상상인플러스저축은행', name: '정기예금', region1: '서울', region2: '대전', region3: '충남', price1: 1.8 , price2: 2.1 , price3: 2.1 , price4: 0.0, contactOptions: true, rank: 7, url:'https://www.sangsanginplussb.com/service/main/index.jsp')
# Bank.create(bank: '상상인플러스저축은행', name: '중도해지 괜찮아 정기예금', region1: '서울', region2: '대전', region3: '충남', price1: 0.0 , price2: 0.0 , price3: 0.0 , price4: 0.0, contactOptions: true, rank: 7, url:'https://www.sangsanginplussb.com/service/main/index.jsp')
# Bank.create(bank: '상상인플러스저축은행', name: '비대면 정기예금', region1: '서울', region2: '대전', region3: '충남', price1: 1.8 , price2: 2.1 , price3: 2.1 , price4: 0.0, contactOptions: false, rank: 7, url:'https://www.sangsanginplussb.com/service/main/index.jsp')
# Bank.create(bank: '상상인플러스저축은행', name: 'e-정기예금', region1: '서울', region2: '대전', region3: '충남', price1: 1.8 , price2: 2.1 , price3: 2.1 , price4: 0.0, contactOptions: false, rank: 7, url:'https://www.sangsanginplussb.com/service/main/index.jsp')
# Bank.create(bank: '세람저축은행', name: 'e-정기예금', region1: '경기', price1: 1.5 , price2: 2.0 , price3: 2.1 , price4: 2.1, contactOptions: false, rank: 43, url:'https://bank.daishin.com/')
# Bank.create(bank: '세람저축은행', name: '회전식 정기예금(비대면 변동금리)', region1: '경기', price1: 0.0 , price2: 2.1 , price3: 2.1 , price4: 2.1, contactOptions: false, rank: 43, url:'https://www.serambank.co.kr/main.html/')
# Bank.create(bank: '세람저축은행', name: '회전식 정기예금(변동금리)', region1: '경기', price1: 0.0 , price2: 2.0 , price3: 2.0 , price4: 2.0, contactOptions: true,rank: 43, url:'https://www.serambank.co.kr/main.html/')
# Bank.create(bank: '세람저축은행', name: '정기예금(비대면)', region1: '경기', price1: 1.5 , price2: 2.0 , price3: 2.1 , price4: 2.1, contactOptions: false, rank: 43, url:'https://www.serambank.co.kr/main.html/')
# Bank.create(bank: '세람저축은행', name: '정기예금', region1: '경기', price1: 1.4 , price2: 1.9 , price3: 2.0 , price4: 2.0, contactOptions: true, rank: 43, url:'https://www.serambank.co.kr/main.html/')
# Bank.create(bank: '센트럴저축은행', name: '정기예금 (인터넷뱅킹스마트뱅킹비대면)', region1: '광주', price1: 1.7, price2: 1.7 , price3: 2.0 , price4: 0.0, contactOptions: false, rank: 43, url:'https://www.serambank.co.kr/main.html/')
# Bank.create(bank: '센트럴저축은행', name: '정기예금', region1: '광주', price1: 1.7 , price2: 2.0 , price3: 0.0 , price4: 0.0, contactOptions: true, rank: 68, url:'https://www.centralbank.co.kr/main.act')
# Bank.create(bank: '솔브레인저축은행', name: '정기예금(비대면)', region1: '부산', price1: 1.6 , price2: 1.9 , price3: 1.9 , price4: 0.0, contactOptions: false, rank: 68, url: 'https://www.soulbrainsb.co.kr/index.asp')
# Bank.create(bank: '솔브레인저축은행', name: '정기예금', region1: '부산', price1: 1.6 , price2: 1.9 , price3: 1.9 , price4: 0.0, contactOptions: true, rank: 58, url: 'https://www.soulbrainsb.co.kr/index.asp')
# Bank.create(bank: '스마트저축은행', name: 'e-정기예금', region1: '서울', region2: '경기', region3: '광주', region4: '전남', region5: '전북', region6: '제주', price1: 1.6 , price2: 2.05 , price3: 2.08 , price4: 2.1, contactOptions: false, rank: 58, url: 'https://www.smartbank.co.kr/HMA0001')
# Bank.create(bank: '스마트저축은행', name: 'e-로운 정기예금', region1: '서울', region2: '경기', region3: '광주', region4: '전남', region5: '전북', region6: '제주', price1: 1.6 , price2: 2.05 , price3: 2.08 , price4: 2.1, contactOptions: false, rank: 21, url: 'https://www.smartbank.co.kr/HMA0001')
# Bank.create(bank: '스마트저축은행', name: '정기예금', region1: '서울', region2: '경기', region3: '광주', region4: '전남', region5: '전북', region6: '제주', price1: 1.6 , price2: 2.0 , price3: 2.03 , price4: 2.05, contactOptions: true, rank: 21, url: 'https://www.smartbank.co.kr/HMA0001')
# Bank.create(bank: '스카이저축은행', name: '정기예금', region1: '서울', price1: 1.7 , price2: 2.0 , price3: 2.0 , price4: 2.0, contactOptions: true, rank: 46, url: 'https://www.skysb.co.kr/main.act')
# Bank.create(bank: '스카이저축은행', name: 'e-정기예금 b-정기예금', region1: '서울', price1: 1.8 , price2: 2.1 , price3: 2.1 , price4: 2.1, contactOptions: false, rank: 46, url: 'https://www.skysb.co.kr/main.act')
# Bank.create(bank: '스타저축은행', name: '스타e-정기예금', region1: '전북', price1: 1.6 , price2: 2.0 , price3: 2.0 , price4: 2.0, contactOptions: false, rank: 67, url: 'http://www.e-starbank.co.kr/')
# Bank.create(bank: '스타저축은행', name: '정기예금', region1: '전북', price1: 1.6 , price2: 2.0 , price3: 2.0 , price4: 2.0, contactOptions: true, rank: 67, url: 'http://www.e-starbank.co.kr/')
# Bank.create(bank: '신한저축은행', name: 'e-정기예금', region1: '서울', region2: '경기', price1: 1.5 , price2: 1.9 , price3: 2.0 , price4: 2.1, contactOptions: false, rank: 16, url: 'https://www.shinhansavings.com/main_0000A_00.act')
# Bank.create(bank: '신한저축은행', name: '정기예금', region1: '서울', region2: '경기', price1: 1.4 , price2: 1.8 , price3: 1.9 , price4: 2.0, contactOptions: true, rank: 16, url: 'https://www.shinhansavings.com/main_0000A_00.act')
# Bank.create(bank: '신한저축은행', name: '더드림정기예금', region1: '서울', region2: '경기', price1: 0.0 , price2: 1.9 , price3: 1.9 , price4: 1.9, contactOptions: true, rank: 16, url: 'https://www.shinhansavings.com/main_0000A_00.act')
# Bank.create(bank: '신한저축은행', name: 'smart-정기예금', region1: '서울', region2: '경기', price1: 1.5 , price2: 1.9 , price3: 2.0 , price4: 2.1, contactOptions: true, rank: 16, url: 'https://www.shinhansavings.com/main_0000A_00.act')
# Bank.create(bank: '아산저축은행', name: 'SB톡톡-정기예금', region1: '충남', price1: 0.0 , price2: 2.0 , price3: 2.0 , price4: 2.0, contactOptions: false, rank: 60, url: 'https://www.asanbank.co.kr/main.act')
# Bank.create(bank: '아산저축은행', name: '정기예금', region1: '충남', price1: 1.5 , price2: 2.0 , price3: 2.0 , price4: 2.0, contactOptions: true, rank: 60, url: 'https://www.asanbank.co.kr/main.act')
# Bank.create(bank: '아산저축은행', name: 'e-정기예금', region1: '충남', price1: 0.0 , price2: 2.0 , price3: 2.0 , price4: 2.0, contactOptions: false, rank: 60, url: 'https://www.asanbank.co.kr/main.act')
# Bank.create(bank: '아주저축은행', name: '정기예금', region1: '서울', region2: '충북', price1: 1.4 , price2: 1.8 , price3: 1.8 , price4: 1.8, contactOptions: true, rank: 32, url: 'https://www.ajusavingsbank.co.kr/')
# Bank.create(bank: '아주저축은행', name: 'e-정기예금', region1: '서울', region2: '충북', price1: 1.4 , price2: 1.9 , price3: 1.9 , price4: 1.9, contactOptions: false, rank: 32, url: 'https://www.ajusavingsbank.co.kr/')
# Bank.create(bank: '아주저축은행', name: '아주비대면정기예금', region1: '서울', region2: '충북', price1: 1.4 , price2: 1.9 , price3: 1.9 , price4: 1.9, contactOptions: false, rank: 32, url: 'https://www.ajusavingsbank.co.kr/')
# Bank.create(bank: '안국저축은행', name: '정기예금(비대면)', region1: '경기', price1: 1.8 , price2: 2.1 , price3: 2.1 , price4: 0.0, contactOptions: false, rank: 55, url: 'https://www.angukbank.co.kr/main.act')
# Bank.create(bank: '안국저축은행', name: 'e-정기예금', region1: '경기', price1: 1.8 , price2: 2.1 , price3: 2.1 , price4: 0.0, contactOptions: false, rank: 55, url: 'https://www.angukbank.co.kr/main.act')
# Bank.create(bank: '안국저축은행', name: '정기예금', region1: '경기', price1: 1.8 , price2: 2.0 , price3: 2.0 , price4: 0.0, contactOptions: true, rank: 55, url: 'https://www.angukbank.co.kr/main.act')
# Bank.create(bank: '안양저축은행', name: '비대면-정기예금', region1: '경기', price1: 1.7 , price2: 2.1 , price3: 2.1 , price4: 2.1, contactOptions: false, rank: 33, url: 'https://www.anyangbank.co.kr/main.act')
# Bank.create(bank: '안양저축은행', name: '정기예금', region1: '경기', price1: 1.7 , price2: 2.05 , price3: 2.05 , price4: 2.05, contactOptions: true, rank: 33, url: 'https://www.anyangbank.co.kr/main.act')
# Bank.create(bank: '애큐온저축은행', name: '인터넷정기예금', region1: '서울', region2: '부산', price1: 1.55 , price2: 1.95 , price3: 2.05 , price4: 2.15, contactOptions: false, rank: 24, url: 'https://www.acuonsb.co.kr/')
# Bank.create(bank: '애큐온저축은행', name: '모바일정기예금', region1: '서울', region2: '부산', price1: 1.6 , price2: 2.0 , price3: 2.1 , price4: 2.2, contactOptions: false, rank: 24, url: 'https://www.acuonsb.co.kr/')
# Bank.create(bank: '애큐온저축은행', name: '정기예금', region1: '서울', region2: '부산', price1: 1.5 , price2: 1.9 , price3: 2.0 , price4: 2.1, contactOptions: true, rank: 24, url: 'https://www.acuonsb.co.kr/')
# Bank.create(bank: '애큐온저축은행', name: '플러스회전식정기예금(변동금리)', region1: '서울', region2: '부산', price1: 0.0 , price2: 0.0 , price3: 0.0 , price4: 1.9, contactOptions: true, rank: 24, url: 'https://www.acuonsb.co.kr/')
# Bank.create(bank: '에스앤티저축은행', name: '정기예금', region1: '경남', price1: 1.6 , price2: 2.0 , price3: 2.1 , price4: 2.2, contactOptions: true, rank: 56, url: 'http://www.hisntm.com/2013/main.html')
# Bank.create(bank: '에스앤티저축은행', name: '정기예금(비대면)', region1: '경남', price1: 1.6 , price2: 2.1 , price3: 2.2 , price4: 2.3, contactOptions: false, rank: 56, url: 'http://www.hisntm.com/2013/main.html')
# Bank.create(bank: '엠에스저축은행', name: 'e-정기예금', region1: '대구', region2: '경북', price1: 1.7 , price2: 2.0 , price3: 2.2 , price4: 2.2, contactOptions: false, rank: 69, url: 'https://www.mssb.co.kr/main.act')
# Bank.create(bank: '엠에스저축은행', name: '정기예금', region1: '대구', region2: '경북', price1: 1.7 , price2: 2.0 , price3: 2.2 , price4: 2.2, contactOptions: true, rank: 69, url: 'https://www.mssb.co.kr/main.act')
# Bank.create(bank: '영진저축은행', name: 'm-정기예금', region1: '경기', price1: 1.8 , price2: 2.1 , price3: 2.2 , price4: 0.0, contactOptions: false, rank: 65, url: 'https://www.yjbank.co.kr/')
# Bank.create(bank: '영진저축은행', name: 'e-정기예금', region1: '경기', price1: 1.8 , price2: 2.1 , price3: 2.2 , price4: 0.0, contactOptions: false, rank: 65, url: 'https://www.yjbank.co.kr/')
# Bank.create(bank: '영진저축은행', name: '정기예금', region1: '경기', price1: 1.8 , price2: 2.0 , price3: 2.1 , price4: 0.0, contactOptions: true, rank: 65, url: 'https://www.yjbank.co.kr/')
# Bank.create(bank: '영진저축은행', name: 'SB톡톡-정기예금', region1: '경기', price1: 1.8 , price2: 2.1 , price3: 2.2 , price4: 0.0, contactOptions: false, rank: 65, url: 'https://www.yjbank.co.kr/')
# Bank.create(bank: '예가람저축은행', name: '정기예금', region1: '서울', region2: '울산', region3: '경남', price1: 1.25 , price2: 1.8 , price3: 1.85 , price4: 1.9, contactOptions: true, rank: 23, url: 'https://www.yegaramsb.co.kr/home')
# Bank.create(bank: '예가람저축은행', name: '안심Plus 정기예금', region1: '서울', region2: '울산', region3: '경남', price1: 0.0 , price2: 0.0 , price3: 0.0 , price4: 1.9, contactOptions: true, rank: 23, url: 'https://www.yegaramsb.co.kr/home')
# Bank.create(bank: '예가람저축은행', name: 'e-안심Plus 정기예금', region1: '서울', region2: '울산', region3: '경남', price1: 0.0 , price2: 0.0 , price3: 0.0 , price4: 2.0, contactOptions: false, rank: 23, url: 'https://www.yegaramsb.co.kr/home')
# Bank.create(bank: '예가람저축은행', name: 'e-정기예금', region1: '서울', region2: '울산', region3: '경남', price1: 1.35 , price2: 1.9 , price3: 1.95 , price4: 2.0, contactOptions: false, rank: 23, url: 'https://www.yegaramsb.co.kr/home')
# Bank.create(bank: '오성저축은행', name: '정기예금', region1: '경북', price1: 1.4 , price2: 1.89 , price3: 1.89 , price4: 1.89, contactOptions: true, rank: 74, url: 'https://www.osungbank.co.kr/main.act')
# Bank.create(bank: '오투저축은행', name: '비대면 정기예금', region1: '대전', region2: '충남', price1: 1.6 , price2: 1.8 , price3: 1.8 , price4: 1.8, contactOptions: false, rank: 45, url: 'https://www.o2banking.com/main.act')
# Bank.create(bank: '오투저축은행', name: '정기예금', region1: '대전', region2: '충남', price1: 1.6 , price2: 1.9 , price3: 1.9 , price4: 1.9, contactOptions: true, rank: 45, url: 'https://www.o2banking.com/main.act')
# Bank.create(bank: '우리저축은행', name: '정기예금', region1: '부산', price1: 1.5 , price2: 2.0 , price3: 2.0 , price4: 0.0, contactOptions: true, rank: 70, url: 'https://wooleebank.co.kr/web/')
# Bank.create(bank: '웰컴저축은행', name: 'WELCOME 릴레이정기예금', region1: '서울', region2: '경기', price1: 0, price2: 2.01, price3: 2.02, price4: 0, contactOptions: true, rank: 3, url: 'https://www.welcomesbdirect.co.kr/')
# Bank.create(bank: '웰컴저축은행', name: 'e-정기예금', region1: '서울', region2: '경기', price1: 1.4, price2: 2.11, price3: 2.12, price4: 2.15, contactOptions: false, rank: 3, url: 'https://www.welcomesbdirect.co.kr/')
# Bank.create(bank: '웰컴저축은행', name: 'm-정기예금', region1: '서울', region2: '경기', price1: 1.4, price2: 2.11, price3: 2.12, price4: 2.15, contactOptions: false, rank: 3, url: 'https://www.welcomesbdirect.co.kr/')
# Bank.create(bank: '웰컴저축은행', name: '정기예금', region1: '서울', region2: '경기', price1: 1.4, price2: 2.01, price3: 2.02, price4: 2.05, contactOptions: true, rank: 3, url: 'https://www.welcomesbdirect.co.kr/')
# Bank.create(bank: '유니온저축은행', name: '정기예금', region1: '대구', price1: 1.6, price2: 1.8, price3: 1.9, price4: 0, contactOptions: true, rank: 52, url: 'https://www.kusb.co.kr/contents/main/')
# Bank.create(bank: '유안타저축은행', name: '정기예금', region1: '서울', price1: 1.55, price2: 1.85, price3: 1.85, price4: 1.85, contactOptions: true, rank: 42, url: 'https://www.yuantasavings.co.kr/main.act')
# Bank.create(bank: '유안타저축은행', name: '회전정기예금 (변동금리)', region1: '서울', price1: 0, price2: 1.85, price3: 1.85, price4: 1.85, contactOptions: true, rank: 42, url: 'https://www.yuantasavings.co.kr/main.act')
# Bank.create(bank: '유안타저축은행', name: 'e-정기예금', region1: '서울', price1: 1.55, price2: 1.85, price3: 1.85, price4: 1.85, contactOptions: false, rank: 42, url: 'https://www.yuantasavings.co.kr/main.act')
# Bank.create(bank: '유안타저축은행', name: '정기예금', region1: '서울', price1: 1.5, price2: 1.8, price3: 1.8, price4: 1.8, contactOptions: true, rank: 42, url: 'https://www.yuantasavings.co.kr/main.act')
# Bank.create(bank: '유진저축은행', name: 'e회전정기예금', region1: '서울', region2: '경기', price1: 0, price2: 1.95, price3: 1.95, price4: 1.95, contactOptions: true, rank: 8, url: 'https://www.eugenebank.com/main.do')
# Bank.create(bank: '유진저축은행', name: '자유해지정기예금', region1: '서울', region2: '경기', price1: 0, price2: 0, price3: 0, price4: 1.7, contactOptions: true, rank: 8, url: 'https://www.eugenebank.com/main.do')
# Bank.create(bank: '유진저축은행', name: 'e정기예금', region1: '서울', region2: '경기', price1: 1.3, price2: 1.95, price3: 1.95, price4: 0, contactOptions: true, rank: 8, url: 'https://www.eugenebank.com/main.do')
# Bank.create(bank: '유진저축은행', name: '정기예금', region1: '서울', region2: '경기', price1: 1.3, price2: 1.9, price3: 1.9, price4: 0, contactOptions: true, rank: 8, url: 'https://www.eugenebank.com/main.do')
# Bank.create(bank: '유진저축은행', name: '회전정기예금', region1: '서울', region2: '경기', price1: 0, price2: 1.95, price3: 1.95, price4: 1.95, contactOptions: true, rank: 8, url: 'https://www.eugenebank.com/main.do')
# Bank.create(bank: '유진저축은행', name: 'e자유해지정기예금', region1: '서울', region2: '경기', price1: 0, price2: 0, price3: 0, price4: 1.8, contactOptions: false, rank: 8, url: 'https://www.eugenebank.com/main.do')
# Bank.create(bank: '융창저축은행', name: 'e정기예금', region1: '경기', price1: 1.5, price2: 1.9, price3: 1.9, price4: 1.9, contactOptions: false, rank: 66, url: 'https://www.ycbank.co.kr/main.act')
# Bank.create(bank: '융창저축은행', name: '정기예금', region1: '경기', price1: 1.5, price2: 1.9, price3: 1.9, price4: 1.9, contactOptions: true, rank: 66, url: 'https://www.ycbank.co.kr/main.act')
# Bank.create(bank: '인성저축은행', name: 'e-정기예금', region1: '인천', price1: 1.7, price2: 2.1, price3: 2.2, price4: 2.2, contactOptions: true, rank: 34, url: 'https://www.insungsavingsbank.co.kr/')
# Bank.create(bank: '인성저축은행', name: '정기예금', region1: '인천', price1: 1.7, price2: 2, price3: 2.1, price4: 2.1, contactOptions: true, rank: 34, url: 'https://www.insungsavingsbank.co.kr/')
# Bank.create(bank: '인천저축은행', name: 'e-정기예금', region1: '인천', price1: 1.7, price2: 2, price3: 2.1, price4: 2.1, contactOptions: false, rank: 36, url: 'https://www.incheonbank.com/main.act')
# Bank.create(bank: '인천저축은행', name: '정기예금', region1: '인천', price1: 1.7, price2: 2, price3: 2.1, price4: 2.1, contactOptions: true, rank: 36, url: 'https://www.incheonbank.com/main.act')
# Bank.create(bank: '조은저축은행', name: 'e-정기예금', region1: '서울', region2: '전남', price1: 1.5, price2: 1.9, price3: 1.9, price4: 1.9, contactOptions: false, rank: 51, url: 'https://choeunbank.com/')
# Bank.create(bank: '조은저축은행', name: '정기예금', region1: '서울', region2: '전남', price1: 1.5, price2: 1.9, price3: 1.9, price4: 1.9, contactOptions: true, rank: 51, url: 'https://choeunbank.com/')
# Bank.create(bank: '조흥저축은행', name: '정기예금', region1: '경남', price1: 1.7, price2: 2.13, price3: 2.16, price4: 2.14, contactOptions: true, rank: 72, url: 'https://chbank.net/')
# Bank.create(bank: '진주저축은행', name: '정기예금', region1: '부산', region2: '경남', price1: 0, price2: 1.88, price3: 0, price4: 0, contactOptions: true, rank: 62, url: 'https://www.jinjubank.net/main.act')
# Bank.create(bank: '참저축은행', name: '정기예금', region1: '대구', price1: 1.7, price2: 1.9, price3: 2, price4: 0, contactOptions: true, rank: 44, url: 'https://www.charmbank.co.kr/mainView.do')
# Bank.create(bank: '참저축은행', name: '비대면정기예금', region1: '대구', price1: 1.7, price2: 1.9, price3: 2, price4: 0, contactOptions: false, rank: 44, url: 'https://www.charmbank.co.kr/mainView.do')
# Bank.create(bank: '청주저축은행', name: '정기예금', region1: '충남', region2: '충북', price1: 1.7, price2: 2.1, price3: 2.1, price4: 2.1, contactOptions: true, rank: 54, url: 'https://www.cheongjubank.com/main.act')
# Bank.create(bank: '청주저축은행', name: 'E-정기예금', region1: '충남', region2: '충북', price1: 1.7, price2: 2.1, price3: 2.1, price4: 2.1, contactOptions: false, rank: 54, url: 'https://www.cheongjubank.com/main.act')
# Bank.create(bank: '청주저축은행', name: 'E-정기예금', region1: '충남', region2: '충북', price1: 1.7, price2: 2.1, price3: 2.1, price4: 2.1, contactOptions: false, rank: 54, url: 'https://www.cheongjubank.com/main.act')
# Bank.create(bank: '청주저축은행', name: '정기예금', region1: '충남', region2: '충북', price1: 1.7, price2: 2.1, price3: 2.1, price4: 2.1, contactOptions: true, rank: 54, url: 'https://www.cheongjubank.com/main.act')
# Bank.create(bank: '키움저축은행', name: 'SB톡톡정기예금 (비대면)', region1: '서울', price1: 1.7, price2: 2, price3: 2.1, price4: 0, contactOptions: false, rank: 13, url: 'https://www.kiwoombank.com/')
# Bank.create(bank: '키움저축은행', name: '정기예금', region1: '서울', price1: 1.7, price2: 2, price3: 2.1, price4: 0, contactOptions: true, rank: 13, url: 'https://www.kiwoombank.com/')
# Bank.create(bank: '키움저축은행', name: 'e-plus정기예금 (인터넷뱅킹스마트뱅킹)', region1: '서울', price1: 1.7, price2: 2, price3: 2.1, price4: 0, contactOptions: false, rank: 13, url: 'https://www.kiwoombank.com/')
# Bank.create(bank: '키움YES저축은행', name: '정기예금', price1: 1.6, price2: 1.9, region1: '서울', price3: 2.1, price4: 2, contactOptions: true, rank: 18, url: 'https://www.kiwoomyesbank.com')
# Bank.create(bank: '키움YES저축은행', name: '정기예금(인터넷뱅킹스마트뱅킹)', region1: '서울', price1: 1.7, price2: 2, price3: 2.1, price4: 2.1, contactOptions: false, rank: 18, url: 'https://www.kiwoomyesbank.com')
# Bank.create(bank: '키움YES저축은행', name: 'SB톡톡 정기예금(비대면)', region1: '서울', price1: 1.7, price2: 2.1, price3: 2.2, price4: 2.2, contactOptions: false, rank: 18, url: 'https://www.kiwoomyesbank.com')
# Bank.create(bank: '페퍼저축은행', name: '페퍼루 중도해지 Free정기예금', region1: '경기', region2: '광주', region3: '전북', price1: 0, price2: 0, price3: 0, price4: 0, contactOptions: true, rank: 41, url: 'https://m.pepperbank.kr/index.html')
# Bank.create(bank: '페퍼저축은행', name: '회전정기예금 (비대면) (년단위 변동금리상품)', region1: '경기', region2: '광주', region3: '전북', price1: 0, price2: 1.95, price3: 1.95, price4: 1.95, contactOptions: false, rank: 41, url: 'https://m.pepperbank.kr/index.html')
# Bank.create(bank: '페퍼저축은행', name: '정기예금 (비대면)', region1: '경기', region2: '광주', region3: '전북', price1: 1.5, price2: 1.85, price3: 1.95, price4: 2.05, contactOptions: false, rank: 41, url: 'https://m.pepperbank.kr/index.html')
# Bank.create(bank: '페퍼저축은행', name: '정기예금 (인터넷 모바일)', region1: '경기', region2: '광주', region3: '전북', price1: 1.5, price2: 1.85, price3: 1.95, price4: 2.05, contactOptions: false, rank: 41, url: 'https://m.pepperbank.kr/index.html')
# Bank.create(bank: '페퍼저축은행', name: '회전정기예금 (인터넷 모바일) (년단위 변동금리상품)', region1: '경기', region2: '광주', region3: '전북', price1: 0, price2: 1.95, price3: 1.95, price4: 1.95, contactOptions: false, rank: 41, url: 'https://m.pepperbank.kr/index.html')
# Bank.create(bank: '페퍼저축은행', name: '정기예금', region1: '경기', region2: '광주', region3: '전북', price1: 1.5, price2: 1.85, price3: 1.95, price4: 2.05, contactOptions: true, rank: 41, url: 'https://m.pepperbank.kr/index.html')
# Bank.create(bank: '페퍼저축은행', name: '회전정기예금 (년단위 변동금리상품)', region1: '경기', region2: '광주', region3: '전북', price1: 0, price2: 1.95, price3: 1.95, price4: 1.95, contactOptions: true, rank: 41, url: 'https://m.pepperbank.kr/index.html')
# Bank.create(bank: '페퍼저축은행', name: '페퍼루 중도해지 Free정기예금(인터넷모바일)', region1: '경기', region2: '광주', region3: '전북', price1: 0, price2: 0, price3: 0, price4: 0, contactOptions: false, rank: 41, url: 'https://m.pepperbank.kr/index.html')
# Bank.create(bank: '페퍼저축은행', name: '페퍼루 중도해지 Free정기예금(비대면)', region1: '경기', region2: '광주', region3: '전북', price1: 0, price2: 0, price3: 0, price4: 0, contactOptions: false, rank: 41, url: 'https://m.pepperbank.kr/index.html')
# Bank.create(bank: '평택저축은행', name: '정기예금', region1: '경기', price1: 1.5, price2: 1.9, price3: 1.9, price4: 2, contactOptions: true, rank: 49, url: 'https://www.ptbank.co.kr/DepDein0100.act')
# Bank.create(bank: '푸른저축은행', name: '푸른 정기예금', region1: '서울', price1: 1.7, price2: 1.9, price3: 1.9, price4: 0, contactOptions: true, rank: 9, url:'https://www.pureunbank.co.kr/prsb/prwww.html?w2xPath=/w2/itb/main.xml&menu=3&menuNo=303&menuNo=303')
# Bank.create(bank: '하나저축은행', name: '정기예금', region1: '서울', region2: '인천', price1: 1.5, price2: 1.6, price3: 1.7, price4: 1.9, contactOptions: true, rank: 17, url:'https://www.hanasavings.com/')
# Bank.create(bank: '하나저축은행', name: 'Q 비대면정기예금', region1: '서울', region2: '인천', price1: 1.6, price2: 1.7, price3: 1.8, price4: 0, contactOptions: false, rank: 17, url: 'https://www.hanasavings.com/')
# Bank.create(bank: '한국투자저축은행', name: 'e-PLAN 인터넷정기예금', region1: '서울', region2: '인천', region3: '경기', price1: 1.4, price2: 2, price3: 2, price4: 2, contactOptions: false, rank: 5, url:'https://www.kisb.co.kr/ib20/mnu/hom00001')
# Bank.create(bank: '한국투자저축은행', name: '비대면 정기예금', region1: '서울', region2: '인천', region3: '경기', price1: 1.4, price2: 2, price3: 2, price4: 2, contactOptions: false, rank: 5, url:'https://www.kisb.co.kr/ib20/mnu/hom00001')
# Bank.create(bank: '한국투자저축은행', name: '스마트뱅킹 정기예금', region1: '서울', region2: '인천', region3: '경기', price1: 1.4, price2: 2, price3: 2, price4: 2, contactOptions: false, rank: 5, url:'https://www.kisb.co.kr/ib20/mnu/hom00001')
# Bank.create(bank: '한국투자저축은행', name: '정기예금', region1: '서울', region2: '인천', region3: '경기', price1: 1.3, price2: 1.9, price3: 1.9, price4: 1.9, contactOptions: true, rank: 5, url: 'https://www.kisb.co.kr/ib20/mnu/hom00001')
# Bank.create(bank: '한성저축은행', name: 'm-정기예금', region1: '대전', region2: '충남', region3: '충북', price1: 1.7, price2: 2.1, price3: 0, price4: 0, contactOptions: false, rank: 53, url:'https://www.efloancard.co.kr/')
# Bank.create(bank: '한성저축은행', name: 'e-정기예금', region1: '대전', region2: '충남', region3: '충북', price1: 1.7, price2: 2.1, price3: 0, price4: 0, contactOptions: false, rank: 53, url:'https://www.efloancard.co.kr/')
# Bank.create(bank: '한성저축은행', name: '정기예금', region1: '대전', region2: '충남', region3: '충북', price1: 1.7, price2: 2.1, price3: 0, price4: 0, contactOptions: true, rank: 53, url:'https://www.efloancard.co.kr/')
# Bank.create(bank: '한화저축은행', name: '한화가족사랑정기예금', region1: '인천', region2: '경기', price1: 1.6, price2: 1.9, price3: 1.9, price4: 0, contactOptions: true, rank: 25, url:'https://www.hanwhasbank.com/main.act')
# Bank.create(bank: '한화저축은행', name: 'e뱅킹정기예금', region1: '인천', region2: '경기', price1: 1.6, price2: 2, price3: 2, price4: 0, contactOptions: false, rank: 25, url:'https://www.hanwhasbank.com/main.act')
# Bank.create(bank: '한화저축은행', name: '한화자동연장정기예금', region1: '인천', region2: '경기', price1: 1.6, price2: 1.95, price3: 1.95, price4: 0, contactOptions: true, rank: 25, url:'https://www.hanwhasbank.com/main.act')
# Bank.create(bank: '흥국저축은행', name: '비대면 정기예금', region1: '서울', region2: '부산', price1: 1.6, price2: 2, price3: 2, price4: 0, contactOptions: false, rank: 29, url:'https://www.hkbanking.co.kr/sub1/sub1_1.php')
# Bank.create(bank: '흥국저축은행', name: 'S-정기예금', region1: '서울', region2: '부산', price1: 1.6, price2: 2, price3: 2, price4: 0, contactOptions: false, rank: 29, url:'https://www.hkbanking.co.kr/sub1/sub1_1.php')
# Bank.create(bank: '흥국저축은행', name: 'E-정기예금', region1: '서울', region2: '부산', price1: 1.6, price2: 2, price3: 2, price4: 0, contactOptions: false, rank: 29, url:'https://www.hkbanking.co.kr/sub1/sub1_1.php')
# Bank.create(bank: '흥국저축은행', name: '정기예금', region1: '서울', region2: '부산', price1: 1.5, price2: 1.9, price3: 1.9, price4: 0, contactOptions: true, rank: 29, url:'https://www.hkbanking.co.kr/sub1/sub1_1.php')